"""Reporting for the skill optimization pipeline.

Generates human-readable reports from run artifacts:
- latest_report.md — summary of most recent run
- regression_watchlist.md — skills that need attention
- per-skill decision cards
"""

from __future__ import annotations

import json
import time
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent
BENCHMARKS_DIR = BASE_DIR / "benchmarks"
REPORTS_DIR = BASE_DIR / "reports"


def generate_run_report(run_dir: Path) -> str:
    """Generate a markdown report for a single run."""
    summary_path = run_dir / "summary.json"
    if not summary_path.exists():
        return f"# Run Report\n\nNo summary found at {run_dir}\n"

    summary = json.loads(summary_path.read_text())

    lines = [
        "# Skill Optimizer Report",
        "",
        f"**Run ID:** {summary.get('run_id', 'unknown')}",
        f"**Mode:** {summary.get('mode', 'unknown')}",
        f"**Completed:** {summary.get('completed', 'unknown')}",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "|--------|-------|",
        f"| Total Skills | {summary.get('total_skills', 0)} |",
        f"| Processed | {summary.get('processed', 0)} |",
        f"| Accepted | {summary.get('accepted', 0)} |",
        f"| Rejected | {summary.get('rejected', 0)} |",
        f"| Skipped | {summary.get('skipped', 0)} |",
        f"| Errors | {summary.get('errors', 0)} |",
        "",
    ]

    if summary.get("halted"):
        lines.append(f"> **BATCH HALTED:** {summary.get('halt_reason', 'unknown')}")
        lines.append("")

    # Per-skill results
    skills = summary.get("skills", [])
    if skills:
        lines.append("## Per-Skill Results")
        lines.append("")
        lines.append("| Skill | Decision | Score | Delta | Reason |")
        lines.append("|-------|----------|-------|-------|--------|")
        for s in skills:
            baseline = s.get("baseline_score", "")
            candidate = s.get("candidate_score", "")
            delta = s.get("delta", "")
            score_str = f"{baseline}" if baseline else ""
            if candidate:
                score_str = f"{baseline} → {candidate}"
            delta_str = f"{delta:+.4f}" if isinstance(delta, (int, float)) and delta else ""
            reason = s.get("reason", "")[:60]
            lines.append(f"| {s.get('skill', '')} | {s.get('decision', '')} | {score_str} | {delta_str} | {reason} |")
        lines.append("")

    # Accepted changes (if any)
    accepted = [s for s in skills if s.get("decision") == "ACCEPT"]
    if accepted:
        lines.append("## Accepted Changes")
        lines.append("")
        for s in accepted:
            lines.append(f"### {s.get('skill', 'unknown')}")
            lines.append(
                f"- **Score improvement:** {s.get('delta', 0):+.4f}" if isinstance(s.get("delta"), (int, float)) else ""
            )
            lines.append(f"- **Reason:** {s.get('reason', '')}")
            lines.append("")

    lines.append(f"\n---\n*Generated by skill_optimizer at {time.strftime('%Y-%m-%d %H:%M:%S')}*\n")

    return "\n".join(lines)


def generate_regression_watchlist() -> str:
    """Generate a regression watchlist from benchmark history."""
    from tools.skill_optimizer.artifact_writer import load_history

    history = load_history()

    # Group by skill
    skill_history: dict[str, list[dict]] = {}
    for entry in history:
        skill = entry.get("skill", "unknown")
        skill_history.setdefault(skill, []).append(entry)

    lines = [
        "# Regression Watchlist",
        "",
        f"*Updated: {time.strftime('%Y-%m-%d %H:%M:%S')}*",
        "",
    ]

    watchlist_items = []

    for skill, entries in sorted(skill_history.items()):
        # Check for score degradation
        scores = [
            e.get("metrics", {}).get("weighted_score", e.get("baseline_score", 0))
            for e in entries
            if isinstance(e.get("metrics", {}).get("weighted_score", e.get("baseline_score")), (int, float))
        ]

        if len(scores) >= 2:
            recent = scores[-1]
            previous = scores[-2]
            if recent < previous - 0.05:  # significant regression
                watchlist_items.append(
                    {
                        "skill": skill,
                        "previous_score": previous,
                        "current_score": recent,
                        "delta": recent - previous,
                        "reason": "score regression detected",
                    }
                )

        # Check for repeated rejections
        recent_decisions = [e.get("decision") for e in entries[-5:] if e.get("type") == "optimization"]
        rejection_count = sum(1 for d in recent_decisions if d and d.startswith("REJECT"))
        if rejection_count >= 3:
            watchlist_items.append(
                {
                    "skill": skill,
                    "previous_score": None,
                    "current_score": None,
                    "delta": None,
                    "reason": f"repeated rejections ({rejection_count}/5)",
                }
            )

    if watchlist_items:
        lines.append("| Skill | Previous | Current | Delta | Reason |")
        lines.append("|-------|----------|---------|-------|--------|")
        for item in watchlist_items:
            prev = f"{item['previous_score']:.3f}" if item["previous_score"] is not None else "-"
            curr = f"{item['current_score']:.3f}" if item["current_score"] is not None else "-"
            delta = f"{item['delta']:+.3f}" if item["delta"] is not None else "-"
            lines.append(f"| {item['skill']} | {prev} | {curr} | {delta} | {item['reason']} |")
    else:
        lines.append("No items on the watchlist.")

    lines.append("")
    return "\n".join(lines)


def write_reports(run_dir: Path | None = None) -> dict[str, Path]:
    """Write all reports."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}

    # Latest report
    if run_dir:
        report = generate_run_report(run_dir)
        report_path = REPORTS_DIR / "latest_report.md"
        report_path.write_text(report)
        paths["latest_report"] = report_path

    # Regression watchlist
    watchlist = generate_regression_watchlist()
    watchlist_path = REPORTS_DIR / "regression_watchlist.md"
    watchlist_path.write_text(watchlist)
    paths["regression_watchlist"] = watchlist_path

    return paths
