#!/usr/bin/env python3
"""One-time MetaApi account setup for NovaTrade FTMO demo.

Creates a MetaApi cloud account entry for your FTMO MT5 demo/free-trial,
waits for deployment, verifies connectivity, and writes the env file.

Usage:
    python3 scripts/novatrade_metaapi_setup.py \
        --token YOUR_METAAPI_TOKEN \
        --login 12345678 \
        --password 'your_investor_password' \
        --server 'FTMO-Demo' \
        --env-out /etc/novacore/novatrade.env

    # With optional FTMO config:
    python3 scripts/novatrade_metaapi_setup.py \
        --token YOUR_METAAPI_TOKEN \
        --login 12345678 \
        --password 'your_investor_password' \
        --server 'FTMO-Demo' \
        --symbols EURUSD,GBPUSD,USDJPY \
        --campaign 'ftmo-free-trial-march-2026' \
        --env-out /etc/novacore/novatrade.env

Notes:
    - Use your MT5 INVESTOR (read-only) password, not the master password
    - The server name must match exactly (check your FTMO MT5 terminal)
    - Your MetaApi token is from https://app.metaapi.cloud/token
    - This script does NOT store secrets in the repo
"""

from __future__ import annotations

import argparse
import asyncio
import sys
import time


async def setup(args: argparse.Namespace) -> int:
    try:
        from metaapi_cloud_sdk import MetaApi
    except ImportError:
        print("ERROR: metaapi_cloud_sdk not installed")
        print("  pip install metaapi-cloud-sdk")
        return 1

    print("=" * 50)
    print("  MetaApi Account Setup for FTMO Demo")
    print("=" * 50)
    print()

    # --- 1. Initialize SDK ---------------------------------------------------
    print("[1/5] Initializing MetaApi SDK...")
    api = MetaApi(args.token)
    print("  OK")

    # --- 2. Create account ---------------------------------------------------
    print(f"[2/5] Creating cloud account (login={args.login}, server={args.server})...")
    try:
        account = await api.metatrader_account_api.create_account(
            {
                "name": f"FTMO Demo {args.login}",
                "type": "cloud",
                "login": args.login,
                "platform": "mt5",
                "password": args.password,
                "server": args.server,
                "magic": args.magic,
                "quoteStreamingIntervalInSeconds": 2.5,
                "reliability": "high",
            }
        )
        account_id = account.id
        print(f"  Account created: {account_id}")
    except Exception as exc:
        print(f"  FAILED: {exc}")
        print()
        print("Common issues:")
        print("  - Invalid token: check https://app.metaapi.cloud/token")
        print("  - Wrong server name: check MT5 terminal → File → Login to Trade Account")
        print("  - Wrong password: use the INVESTOR password, not master")
        return 2

    # --- 3. Wait for deployment ----------------------------------------------
    print("[3/5] Deploying account (this may take 1-3 minutes)...")
    try:
        await account.deploy()
        await account.wait_deployed(timeout_in_seconds=180)
        print("  Deployed")
    except Exception as exc:
        print(f"  Deploy timeout/error: {exc}")
        print(f"  Account ID is still: {account_id}")
        print("  You can check status at https://app.metaapi.cloud")
        # Don't fail — account may still deploy, write env anyway

    # --- 4. Verify connection ------------------------------------------------
    print("[4/5] Verifying connection...")
    connected = False
    try:
        connection = account.get_rpc_connection()
        await connection.connect()
        await connection.wait_synchronized(timeout_in_seconds=120)

        info = await connection.get_account_information()
        print(f"  Broker:    {info.get('broker', 'unknown')}")
        print(f"  Server:    {info.get('server', 'unknown')}")
        print(f"  Balance:   {info.get('balance', 0)} {info.get('currency', 'USD')}")
        print(f"  Leverage:  1:{info.get('leverage', '?')}")
        print(f"  Name:      {info.get('name', 'unknown')}")
        connected = True

        await connection.close()
    except Exception as exc:
        print(f"  Connection verification failed: {exc}")
        print("  The account may still be deploying — check MetaApi dashboard")

    # --- 5. Write env file ---------------------------------------------------
    print(f"[5/5] Writing env file → {args.env_out}")

    symbols = args.symbols or "EURUSD,GBPUSD,USDJPY"
    campaign = args.campaign or "ftmo-free-trial"

    env_content = f"""# NovaTrade FTMO Demo — auto-generated by novatrade_metaapi_setup.py
# {time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())}

# MetaApi credentials
METAAPI_TOKEN={args.token}
METAAPI_ACCOUNT_ID={account_id}

# NovaTrade core
NOVATRADE_MODE=DEMO
NOVATRADE_DRY_RUN=true
NOVATRADE_SYMBOLS={symbols}
NOVATRADE_TIMEFRAMES=H1,H4

# FTMO profile
FTMO_ENABLED=true
FTMO_CHALLENGE_TYPE=free_trial
FTMO_CAMPAIGN_LABEL={campaign}
# FTMO_SYMBOL_SUFFIX=
# FTMO_SYMBOL_MAP=
"""

    from pathlib import Path

    env_path = Path(args.env_out)
    env_path.parent.mkdir(parents=True, exist_ok=True)
    env_path.write_text(env_content)
    # Restrict permissions — secrets file
    env_path.chmod(0o600)
    print(f"  Written ({env_path}), permissions 600")

    # --- Summary -------------------------------------------------------------
    print()
    print("=" * 50)
    print("  Setup Complete")
    print("=" * 50)
    print()
    print(f"  Account ID:  {account_id}")
    print(f"  Connected:   {'YES' if connected else 'PENDING'}")
    print(f"  Env file:    {args.env_out}")
    print()
    print("  Next steps:")
    print(f"    python3 scripts/novatrade_ftmo.py preflight --env-file {args.env_out}")
    print(
        f"    python3 scripts/novatrade_ftmo.py dry-run --symbol EURUSD"
        f" --side BUY --volume 0.01 --sl 1.0900 --env-file {args.env_out}"
    )
    print()

    return 0


def main() -> None:
    parser = argparse.ArgumentParser(
        description="One-time MetaApi account setup for FTMO demo",
    )
    parser.add_argument("--token", required=True, help="MetaApi API token")
    parser.add_argument("--login", required=True, help="MT5 login number")
    parser.add_argument("--password", required=True, help="MT5 investor (read-only) password")
    parser.add_argument("--server", required=True, help="MT5 server name (exact match)")
    parser.add_argument("--magic", type=int, default=123456, help="Magic number (default: 123456)")
    parser.add_argument("--symbols", default=None, help="Comma-separated symbol list (default: EURUSD,GBPUSD,USDJPY)")
    parser.add_argument("--campaign", default=None, help="Campaign label for evidence tagging")
    parser.add_argument(
        "--env-out",
        default="/etc/novacore/novatrade.env",
        help="Output env file path (default: /etc/novacore/novatrade.env)",
    )

    args = parser.parse_args()
    exit_code = asyncio.get_event_loop().run_until_complete(setup(args))
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
